"""Add wallet and user models

Revision ID: a45ea9422de5
Revises: 9be6eb34992e
Create Date: 2025-01-20 22:45:05.532857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a45ea9422de5'
down_revision: Union[str, None] = '9be6eb34992e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_agent_sessions_agent_id', table_name='agent_sessions')
    op.drop_index('idx_agent_sessions_session_id', table_name='agent_sessions')
    op.drop_index('idx_agent_sessions_user_id', table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('chat_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('seed_phrase', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('private_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('public_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('chat_id', name='users_pkey'),
    sa.UniqueConstraint('chat_id', name='users_chat_id_key')
    )
    op.create_table('agent_sessions',
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('memory', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('agent_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('session_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BIGINT(), server_default=sa.text('(EXTRACT(epoch FROM now()))::bigint'), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('session_id', name='agent_sessions_pkey')
    )
    op.create_index('idx_agent_sessions_user_id', 'agent_sessions', ['user_id'], unique=False)
    op.create_index('idx_agent_sessions_session_id', 'agent_sessions', ['session_id'], unique=False)
    op.create_index('idx_agent_sessions_agent_id', 'agent_sessions', ['agent_id'], unique=False)
    # ### end Alembic commands ###
