name: Build & Push Docker Image
run-name: Build and push ${{ github.event.inputs.tag}}

on:
  workflow_dispatch: # Enable manual trigger
    inputs:
      tag:
        description: "Docker image tag"
        required: true
        default: "v1.0"
      image:
        description: "Docker image name"
        required: true
        default: "ai-agent/pluton-dev"

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ steps.login-ecr.outputs.registry }}/${{inputs.image}}:${{inputs.tag}}
          push: true
          file: Dockerfile
